# Network Monitoring Configuration - Prometheus & Grafana

# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['localhost:9116']
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://10.0.1.1:80
        - http://10.0.1.2:80
        - https://10.0.1.5:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

# alert_rules.yml
groups:
  - name: network_alerts
    rules:
      - alert: HighCPULoad
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU load (instance {{ $labels.instance }})"
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage (instance {{ $labels.instance }})"
          description: "Memory usage is > 90%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance down (instance {{ $labels.instance }})"
          description: "Instance has been down for more than 5 minutes."

      - alert: NetworkInterfaceHighErrorRate
        expr: rate(node_network_transmit_errs_total[5m]) > 0 or rate(node_network_receive_errs_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Network interface errors (instance {{ $labels.instance }})"
          description: "Network interface {{ $labels.device }} showing errors\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: NetworkInterfaceSaturation
        expr: (rate(node_network_receive_bytes_total{device!~"lo"}[1m]) + rate(node_network_transmit_bytes_total{device!~"lo"}[1m])) / node_network_speed_bytes{device!~"lo"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Network interface saturation (instance {{ $labels.instance }})"
          description: "Network interface {{ $labels.device }} utilization > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

# snmp.yml
if_mib:
  walk:
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
  metrics:
    - name: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
      help: The textual name of the interface
      indexes:
        - labelname: ifIndex
          type: gauge
      lookups:
        - labels: [ifIndex]
          labelname: ifDescr
          type: DisplayString

    - name: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: gauge
      help: The type of interface

    - name: ifMtu
      oid: 1.3.6.1.2.1.2.2.1.4
      type: gauge
      help: The MTU of the interface

    - name: ifSpeed
      oid: 1.3.6.1.2.1.2.2.1.5
      type: gauge
      help: The bandwidth of the interface in bits per second

    - name: ifAdminStatus
      oid: 1.3.6.1.2.1.2.2.1.7
      type: gauge
      help: The administrative status of the interface

    - name: ifOperStatus
      oid: 1.3.6.1.2.1.2.2.1.8
      type: gauge
      help: The operational status of the interface

    - name: ifInOctets
      oid: 1.3.6.1.2.1.2.2.1.10
      type: counter
      help: The number of octets received on the interface

    - name: ifInUcastPkts
      oid: 1.3.6.1.2.1.2.2.1.11
      type: counter
      help: The number of unicast packets received on the interface

    - name: ifInErrors
      oid: 1.3.6.1.2.1.2.2.1.14
      type: counter
      help: The number of inbound packets that contained errors

    - name: ifOutOctets
      oid: 1.3.6.1.2.1.2.2.1.16
      type: counter
      help: The number of octets transmitted on the interface

    - name: ifOutUcastPkts
      oid: 1.3.6.1.2.1.2.2.1.17
      type: counter
      help: The number of unicast packets transmitted on the interface

    - name: ifOutErrors
      oid: 1.3.6.1.2.1.2.2.1.20
      type: counter
      help: The number of outbound packets that contained errors

    - name: ifHCInOctets
      oid: 1.3.6.1.2.1.31.1.1.1.6
      type: counter
      help: The number of octets received on the interface, including framing characters

    - name: ifHCOutOctets
      oid: 1.3.6.1.2.1.31.1.1.1.10
      type: counter
      help: The number of octets transmitted on the interface, including framing characters
